import type { KingsLevel } from './types';

// No longer wired into gameplay -- levels are generated at runtime on demand
// (see state/useKingsProgress.ts + generation/). Kept as CLI/dev fixtures
// (`npm run levels -- kings ...`) and a reference for the original
// hand-authored methodology.
//
// Ported directly from signal-arcade-prototype.html. Each region layout was
// generated by a hill-climbing search and independently verified to be:
//  (1) fully solvable by pure logical elimination (hidden-singles + locked-set
//      deductions, no guessing/backtracking), and
//  (2) has exactly one valid solution (confirmed via a separate brute-force
//      backtracking search).
// See the generator notes in signal-arcade-prototype.html's kings module for
// the full methodology if these ever need regenerating.
export const levels: KingsLevel[] = [
  {
    title: 'First Court',
    instructions: 'One king per row, column, and colored realm.',
    n: 5,
    regions: [
      [2, 0, 0, 1, 1],
      [2, 2, 0, 1, 1],
      [2, 2, 0, 1, 1],
      [2, 4, 4, 3, 3],
      [2, 2, 4, 4, 4],
    ],
    solution: [[0, 1], [1, 3], [2, 0], [3, 4], [4, 2]],
  },
  {
    title: 'Twin Realms',
    instructions: "Six realms now — kings still can't touch, even diagonally.",
    n: 6,
    regions: [
      [1, 1, 2, 2, 0, 0],
      [1, 1, 1, 2, 2, 0],
      [1, 1, 1, 2, 2, 2],
      [5, 1, 2, 2, 4, 4],
      [5, 3, 4, 4, 4, 5],
      [5, 5, 5, 5, 5, 5],
    ],
    solution: [[0, 2], [1, 5], [2, 0], [3, 4], [4, 1], [5, 3]],
  },
  {
    title: 'Grand Kingdom',
    instructions: 'The full seven-realm court. Use marks to track eliminated cells.',
    n: 7,
    regions: [
      [3, 3, 3, 0, 0, 0, 0],
      [1, 1, 3, 3, 0, 0, 0],
      [1, 1, 1, 3, 2, 0, 0],
      [1, 1, 3, 3, 2, 2, 0],
      [1, 5, 2, 2, 2, 2, 4],
      [1, 5, 5, 5, 2, 6, 4],
      [1, 5, 5, 5, 6, 6, 4],
    ],
    solution: [[0, 3], [1, 0], [2, 4], [3, 2], [4, 6], [5, 1], [6, 5]],
  },
  {
    n: 7,
    regions: [
      [6, 0, 0, 0, 0, 4, 4],
      [6, 6, 6, 0, 0, 0, 4],
      [6, 3, 0, 0, 0, 3, 4],
      [6, 3, 3, 3, 3, 3, 4],
      [6, 6, 2, 3, 3, 4, 4],
      [6, 6, 2, 4, 4, 4, 5],
      [1, 1, 2, 2, 5, 5, 5],
    ],
    solution: [[0, 5], [1, 3], [2, 0], [3, 4], [4, 2], [5, 6], [6, 1]],
  },
  {
    n: 5,
    regions: [
      [3, 3, 3, 3, 4],
      [3, 0, 3, 3, 1],
      [0, 0, 0, 0, 1],
      [2, 0, 0, 1, 1],
      [2, 2, 2, 2, 2],
    ],
    solution: [[0, 4], [1, 2], [2, 0], [3, 3], [4, 1]],
  },
  {
    n: 5,
    regions: [
      [0, 0, 0, 0, 4],
      [1, 0, 0, 0, 2],
      [1, 1, 2, 2, 2],
      [1, 1, 2, 2, 3],
      [1, 1, 3, 3, 3],
    ],
    solution: [[0, 4], [1, 1], [2, 3], [3, 0], [4, 2]],
  },
  {
    n: 5,
    regions: [
      [1, 1, 1, 4, 4],
      [2, 1, 1, 0, 0],
      [2, 2, 0, 0, 3],
      [2, 2, 3, 3, 3],
      [2, 2, 3, 3, 3],
    ],
    solution: [[0, 4], [1, 1], [2, 3], [3, 0], [4, 2]],
  },
  {
    n: 5,
    regions: [
      [1, 1, 1, 1, 1],
      [4, 4, 1, 2, 2],
      [4, 4, 2, 2, 2],
      [4, 4, 0, 0, 2],
      [0, 0, 0, 0, 3],
    ],
    solution: [[0, 1], [1, 3], [2, 0], [3, 2], [4, 4]],
  },
  {
    n: 5,
    regions: [
      [3, 1, 1, 1, 1],
      [3, 3, 1, 1, 4],
      [2, 4, 1, 1, 4],
      [2, 4, 4, 4, 4],
      [0, 0, 0, 0, 0],
    ],
    solution: [[0, 3], [1, 1], [2, 4], [3, 0], [4, 2]],
  },
  {
    n: 6,
    regions: [
      [5, 5, 4, 4, 4, 2],
      [5, 4, 4, 4, 2, 2],
      [5, 0, 0, 0, 0, 2],
      [3, 0, 0, 0, 0, 2],
      [3, 1, 1, 1, 2, 2],
      [3, 1, 1, 1, 1, 1],
    ],
    solution: [[0, 1], [1, 3], [2, 5], [3, 2], [4, 0], [5, 4]],
  },
  {
    n: 6,
    regions: [
      [2, 2, 2, 4, 4, 4],
      [0, 2, 2, 2, 4, 4],
      [0, 0, 0, 2, 5, 5],
      [0, 0, 0, 3, 3, 5],
      [0, 0, 3, 3, 3, 5],
      [0, 3, 3, 3, 3, 1],
    ],
    solution: [[0, 3], [1, 1], [2, 4], [3, 0], [4, 2], [5, 5]],
  },
  {
    n: 6,
    regions: [
      [3, 2, 2, 2, 2, 5],
      [3, 2, 2, 5, 5, 5],
      [3, 2, 0, 0, 5, 5],
      [3, 2, 0, 0, 0, 5],
      [3, 3, 3, 4, 0, 0],
      [4, 4, 4, 4, 1, 1],
    ],
    solution: [[0, 1], [1, 4], [2, 2], [3, 0], [4, 3], [5, 5]],
  },
  {
    n: 6,
    regions: [
      [1, 1, 1, 3, 3, 3],
      [2, 2, 2, 3, 3, 3],
      [5, 5, 5, 3, 4, 4],
      [5, 5, 4, 4, 4, 4],
      [5, 5, 0, 0, 0, 0],
      [5, 0, 0, 0, 0, 0],
    ],
    solution: [[0, 2], [1, 0], [2, 3], [3, 5], [4, 1], [5, 4]],
  },
];

// Only the very first level gates on the (single, combined) tutorial; every
// other level skips straight to play. See tutorialContent.tsx.
export const levelTutorialKey: Array<string | null> = ['all', null, null, null, null, null, null, null, null, null, null, null, null];
