import type { FindWordsLevel } from '../types';
import type { DifficultyTierKey } from './difficulty';
import type { WordBankLanguage } from './wordbanks';

/**
 * One certified board per (difficulty tier x language), for
 * `createLevelForIndexRobust`'s final fallback stage. Pulled directly from
 * generation/__scripts__/sweep.ts output at each tier's representative
 * rating (10/50/70/90) and hardcoded here -- word placement is reliable
 * enough that the sweep found a valid board on attempt 1 at every rating
 * tried, so this is a genuine safety net, not a board that's ever likely to
 * actually be served. Per (tier, language) -- not one universal board -- so
 * a player deep in a hard tier is never silently handed an easy one, and a
 * French-language player is never silently handed English content. See
 * CLAUDE.md's "never fall back to a lesser solution" rule.
 */
export const SAFE_BOARDS: Record<WordBankLanguage, Record<DifficultyTierKey, FindWordsLevel>> = {
  en: {
    starter: {
      rows: 7,
      cols: 8,
      grid: [
        ['E', 'S', 'O', 'U', 'P', 'V', 'P', 'E'],
        ['R', 'A', 'A', 'A', 'N', 'J', 'U', 'K'],
        ['D', 'R', 'G', 'L', 'C', 'W', 'L', 'S'],
        ['R', 'N', 'I', 'L', 'E', 'G', 'I', 'O'],
        ['A', 'P', 'R', 'V', 'E', 'M', 'W', 'T'],
        ['W', 'U', 'K', 'G', 'E', 'Q', 'O', 'X'],
        ['G', 'O', 'E', 'O', 'B', 'R', 'W', 'N'],
      ],
      placements: [
        { word: 'RIVER', row: 2, col: 1, direction: 'SE' },
        { word: 'LEMON', row: 2, col: 3, direction: 'SE' },
        { word: 'EAGLE', row: 0, col: 0, direction: 'SE' },
        { word: 'DRAW', row: 2, col: 0, direction: 'S' },
        { word: 'SOUP', row: 0, col: 1, direction: 'E' },
      ],
    },
    growing: {
      rows: 10,
      cols: 9,
      grid: [
        ['D', 'H', 'D', 'S', 'L', 'E', 'D', 'B', 'V'],
        ['P', 'Y', 'W', 'V', 'I', 'D', 'E', 'O', 'R'],
        ['W', 'N', 'U', 'R', 'S', 'E', 'O', 'L', 'Z'],
        ['W', 'R', 'P', 'G', 'I', 'Y', 'J', 'L', 'T'],
        ['G', 'U', 'I', 'T', 'A', 'R', 'N', 'U', 'E'],
        ['X', 'L', 'W', 'T', 'K', 'F', 'P', 'U', 'W'],
        ['T', 'N', 'V', 'W', 'E', 'V', 'W', 'N', 'R'],
        ['W', 'I', 'N', 'D', 'O', 'W', 'S', 'W', 'I'],
        ['T', 'R', 'S', 'U', 'M', 'L', 'H', 'F', 'S'],
        ['U', 'R', 'W', 'J', 'Q', 'H', 'Q', 'A', 'T'],
      ],
      placements: [
        { word: 'WINDOW', row: 7, col: 0, direction: 'E' },
        { word: 'GUITAR', row: 4, col: 0, direction: 'E' },
        { word: 'WRITE', row: 2, col: 0, direction: 'SE' },
        { word: 'WRIST', row: 5, col: 8, direction: 'S' },
        { word: 'VIDEO', row: 1, col: 3, direction: 'E' },
        { word: 'NURSE', row: 2, col: 1, direction: 'E' },
        { word: 'SLED', row: 0, col: 3, direction: 'E' },
      ],
    },
    skilled: {
      rows: 11,
      cols: 11,
      grid: [
        ['A', 'T', 'T', 'K', 'N', 'I', 'G', 'U', 'A', 'N', 'A'],
        ['P', 'P', 'L', 'S', 'S', 'E', 'K', 'P', 'Q', 'W', 'F'],
        ['C', 'U', 'E', 'D', 'E', 'A', 'G', 'O', 'A', 'O', 'A'],
        ['Y', 'Q', 'J', 'L', 'D', 'H', 'M', 'T', 'S', 'D', 'L'],
        ['W', 'F', 'E', 'G', 'I', 'O', 'C', 'A', 'Y', 'A', 'C'],
        ['M', 'W', 'D', 'G', 'S', 'M', 'Q', 'T', 'J', 'E', 'O'],
        ['U', 'H', 'W', 'M', 'Q', 'K', 'S', 'O', 'U', 'M', 'N'],
        ['G', 'R', 'D', 'B', 'R', 'A', 'I', 'N', 'H', 'G', 'E'],
        ['Z', 'X', 'R', 'E', 'V', 'I', 'R', 'D', 'G', 'W', 'S'],
        ['N', 'U', 'P', 'T', 'N', 'E', 'U', 'T', 'R', 'Y', 'I'],
        ['T', 'D', 'T', 'L', 'R', 'F', 'N', 'B', 'G', 'J', 'B'],
      ],
      placements: [
        { word: 'IGUANA', row: 0, col: 5, direction: 'E' },
        { word: 'MEADOW', row: 6, col: 9, direction: 'N' },
        { word: 'FALCON', row: 1, col: 10, direction: 'S' },
        { word: 'DRIVER', row: 8, col: 7, direction: 'W' },
        { word: 'POTATO', row: 1, col: 7, direction: 'S' },
        { word: 'CHEST', row: 4, col: 6, direction: 'NW' },
        { word: 'BRAIN', row: 7, col: 3, direction: 'E' },
        { word: 'SMILE', row: 6, col: 6, direction: 'NW' },
        { word: 'MASK', row: 3, col: 6, direction: 'NW' },
      ],
    },
    expert: {
      rows: 12,
      cols: 13,
      grid: [
        ['I', 'Q', 'N', 'C', 'M', 'I', 'F', 'R', 'E', 'E', 'Z', 'E', 'D'],
        ['K', 'K', 'E', 'Y', 'B', 'O', 'A', 'R', 'D', 'T', 'X', 'V', 'Z'],
        ['F', 'J', 'N', 'J', 'R', 'E', 'R', 'E', 'B', 'M', 'E', 'F', 'U'],
        ['C', 'R', 'R', 'Y', 'E', 'Y', 'G', 'K', 'M', 'T', 'Q', 'G', 'A'],
        ['W', 'E', 'D', 'X', 'B', 'R', 'S', 'O', 'E', 'H', 'P', 'G', 'T'],
        ['E', 'D', 'Z', 'B', 'M', 'O', 'C', 'C', 'I', 'U', 'A', 'R', 'E'],
        ['M', 'I', 'I', 'B', 'E', 'M', 'I', 'M', 'R', 'M', 'J', 'V', 'H'],
        ['Q', 'C', 'U', 'A', 'M', 'E', 'E', 'U', 'I', 'B', 'Z', 'C', 'Y'],
        ['Q', 'D', 'U', 'X', 'E', 'M', 'N', 'G', 'A', 'R', 'E', 'A', 'E'],
        ['Z', 'F', 'E', 'K', 'R', 'X', 'C', 'K', 'R', 'C', 'U', 'T', 'H'],
        ['N', 'F', 'R', 'V', 'X', 'A', 'E', 'Z', 'P', 'L', 'F', 'C', 'V'],
        ['O', 'P', 'H', 'O', 'T', 'O', 'F', 'P', 'D', 'K', 'Q', 'H', 'D'],
      ],
      placements: [
        { word: 'REMEMBER', row: 9, col: 4, direction: 'N' },
        { word: 'KEYBOARD', row: 1, col: 1, direction: 'E' },
        { word: 'PRAIRIE', row: 10, col: 8, direction: 'N' },
        { word: 'SCIENCE', row: 4, col: 6, direction: 'S' },
        { word: 'FREEZE', row: 0, col: 6, direction: 'E' },
        { word: 'MEMORY', row: 8, col: 5, direction: 'N' },
        { word: 'THUMB', row: 3, col: 9, direction: 'S' },
        { word: 'PHOTO', row: 11, col: 1, direction: 'E' },
        { word: 'EMBER', row: 2, col: 10, direction: 'W' },
        { word: 'CATCH', row: 7, col: 11, direction: 'S' },
        { word: 'CIDER', row: 7, col: 1, direction: 'N' },
      ],
    },
  },
  fr: {
    starter: {
      rows: 8,
      cols: 8,
      grid: [
        ['M', 'A', 'R', 'I', 'N', 'R', 'C', 'O'],
        ['U', 'D', 'Y', 'P', 'J', 'B', 'P', 'V'],
        ['I', 'A', 'D', 'M', 'S', 'M', 'F', 'K'],
        ['G', 'I', 'X', 'R', 'H', 'V', 'A', 'L'],
        ['E', 'G', 'N', 'J', 'O', 'J', 'Q', 'T'],
        ['I', 'L', 'W', 'A', 'R', 'N', 'G', 'H'],
        ['U', 'E', 'N', 'Y', 'T', 'P', 'M', 'Y'],
        ['O', 'Y', 'F', 'O', 'I', 'E', 'F', 'M'],
      ],
      placements: [
        { word: 'SHORT', row: 2, col: 4, direction: 'S' },
        { word: 'MARIN', row: 0, col: 0, direction: 'E' },
        { word: 'AIGLE', row: 2, col: 1, direction: 'S' },
        { word: 'FOIE', row: 7, col: 2, direction: 'E' },
        { word: 'THYM', row: 4, col: 7, direction: 'S' },
      ],
    },
    growing: {
      rows: 9,
      cols: 10,
      grid: [
        ['G', 'P', 'C', 'O', 'U', 'S', 'I', 'N', 'V', 'I'],
        ['J', 'U', 'V', 'I', 'O', 'L', 'E', 'T', 'R', 'G'],
        ['H', 'V', 'W', 'E', 'G', 'P', 'E', 'G', 'U', 'R'],
        ['C', 'O', 'K', 'M', 'D', 'P', 'J', 'G', 'R', 'O'],
        ['H', 'G', 'Z', 'A', 'W', 'T', 'L', 'S', 'S', 'T'],
        ['È', 'X', 'A', 'N', 'W', 'B', 'C', 'E', 'R', 'T'],
        ['V', 'E', 'R', 'G', 'A', 'R', 'A', 'G', 'E', 'E'],
        ['R', 'A', 'T', 'U', 'S', 'O', 'U', 'P', 'E', 'P'],
        ['E', 'K', 'K', 'E', 'V', 'M', 'U', 'I', 'K', 'B'],
      ],
      placements: [
        { word: 'CHÈVRE', row: 3, col: 0, direction: 'S' },
        { word: 'COUSIN', row: 0, col: 2, direction: 'E' },
        { word: 'GARAGE', row: 6, col: 3, direction: 'E' },
        { word: 'VIOLET', row: 1, col: 2, direction: 'E' },
        { word: 'GROTTE', row: 1, col: 9, direction: 'S' },
        { word: 'MANGUE', row: 3, col: 3, direction: 'S' },
        { word: 'SOUPE', row: 7, col: 4, direction: 'E' },
      ],
    },
    skilled: {
      rows: 10,
      cols: 10,
      grid: [
        ['E', 'V', 'A', 'C', 'H', 'E', 'H', 'R', 'F', 'C'],
        ['L', 'I', 'Z', 'G', 'T', 'E', 'A', 'X', 'O', 'I'],
        ['E', 'A', 'N', 'O', 'H', 'T', 'Y', 'P', 'N', 'L'],
        ['G', 'L', 'E', 'Q', 'R', 'R', 'S', 'I', 'I', 'I'],
        ['N', 'A', 'H', 'H', 'N', 'X', 'I', 'M', 'M', 'S'],
        ['I', 'B', 'C', 'C', 'O', 'E', 'A', 'I', 'O', 'A'],
        ['L', 'O', 'U', 'I', 'Z', 'M', 'L', 'T', 'D', 'B'],
        ['W', 'L', 'P', 'J', 'H', 'D', 'A', 'S', 'K', 'T'],
        ['O', 'K', 'A', 'R', 'C', 'S', 'P', 'R', 'S', 'Y'],
        ['B', 'T', 'C', 'T', 'H', 'O', 'Z', 'V', 'D', 'C'],
      ],
      placements: [
        { word: 'CAPUCHE', row: 9, col: 2, direction: 'N' },
        { word: 'BASILIC', row: 6, col: 9, direction: 'N' },
        { word: 'BOWLING', row: 9, col: 0, direction: 'N' },
        { word: 'DOMINO', row: 6, col: 8, direction: 'N' },
        { word: 'HOMARD', row: 4, col: 3, direction: 'SE' },
        { word: 'PYTHON', row: 2, col: 7, direction: 'W' },
        { word: 'PALAIS', row: 8, col: 6, direction: 'N' },
        { word: 'VACHE', row: 0, col: 1, direction: 'E' },
        { word: 'BALAI', row: 5, col: 1, direction: 'N' },
      ],
    },
    expert: {
      rows: 13,
      cols: 13,
      grid: [
        ['A', 'I', 'C', 'E', 'B', 'C', 'C', 'A', 'R', 'O', 'T', 'T', 'E'],
        ['Z', 'N', 'X', 'H', 'L', 'L', 'P', 'K', 'P', 'B', 'O', 'G', 'A'],
        ['E', 'G', 'W', 'V', 'E', 'O', 'U', 'M', 'X', 'M', 'J', 'J', 'G'],
        ['I', 'I', 'E', 'A', 'Q', 'V', 'S', 'U', 'T', 'Z', 'V', 'E', 'S'],
        ['G', 'M', 'U', 'J', 'A', 'A', 'A', 'S', 'S', 'V', 'I', 'D', 'S'],
        ['O', 'R', 'B', 'P', 'Y', 'C', 'W', 'L', 'U', 'H', 'W', 'R', 'I'],
        ['L', 'U', 'L', 'S', 'J', 'E', 'R', 'O', 'Z', 'O', 'X', 'A', 'N'],
        ['O', 'O', 'A', 'Q', 'T', 'G', 'U', 'È', 'A', 'R', 'B', 'T', 'O'],
        ['I', 'F', 'I', 'I', 'A', 'K', 'U', 'T', 'M', 'X', 'S', 'U', 'I'],
        ['B', 'Q', 'R', 'E', 'R', 'O', 'L', 'P', 'X', 'E', 'C', 'O', 'V'],
        ['I', 'I', 'E', 'G', 'K', 'A', 'J', 'K', 'T', 'Z', 'E', 'M', 'A'],
        ['N', 'Y', 'A', 'L', 'E', 'N', 'N', 'U', 'T', 'D', 'P', 'B', 'I'],
        ['J', 'Y', 'U', 'O', 'O', 'C', 'V', 'K', 'H', 'L', 'Q', 'J', 'U'],
      ],
      placements: [
        { word: 'BOUSSOLE', row: 7, col: 10, direction: 'NW' },
        { word: 'BLAIREAU', row: 5, col: 2, direction: 'S' },
        { word: 'EXPLORER', row: 9, col: 9, direction: 'W' },
        { word: 'BIOLOGIE', row: 9, col: 0, direction: 'N' },
        { word: 'MOUTARDE', row: 10, col: 11, direction: 'N' },
        { word: 'CAROTTE', row: 0, col: 6, direction: 'E' },
        { word: 'FOURMI', row: 8, col: 1, direction: 'N' },
        { word: 'TUNNEL', row: 11, col: 8, direction: 'W' },
        { word: 'CHEVAL', row: 0, col: 2, direction: 'SE' },
        { word: 'AVION', row: 10, col: 12, direction: 'N' },
        { word: 'CRÈME', row: 5, col: 5, direction: 'SE' },
      ],
    },
  },
};
