import type { RelayLevel } from './types';

// Ported directly from the relay-app-prototype_1.html prototype (same 3
// levels, same budgets/ranges). Grid is 8x8, coordinates are
// (col, row) zero-indexed from the top-left.
export const GRID_COLS = 8;
export const GRID_ROWS = 8;

// Plain [0..7] index lists, handy for generating wall patterns that span the
// full grid (see the mirror levels near the end of this file).
const GRID_X = Array.from({ length: GRID_COLS }, (_, i) => i);
const GRID_Y = Array.from({ length: GRID_ROWS }, (_, i) => i);

// Builds a wall list from an explicit "these cells are the open path/floor,
// everything else is wall" set -- reads a lot more like an actual maze
// layout than listing wall cells one by one. `open` entries are "x,y" strings.
function wallsExcept(open: string[]): { x: number; y: number }[] {
  const openSet = new Set(open);
  return GRID_X.flatMap((x) => GRID_Y.filter((y) => !openSet.has(`${x},${y}`)).map((y) => ({ x, y })));
}

export const levels: RelayLevel[] = [
  {
    title: 'Signal 101',
    instructions: 'Bridge the gap. Place relay nodes to extend the blue signal from source to receiver.',
    walls: [],
    sources: [{ color: 'blue', x: 0, y: 0, range: 3 }],
    receivers: [{ color: 'blue', x: 6, y: 6 }],
    budgets: { blue: 2 },
    relayRange: 3,
    interferenceDistance: 0,
  },
  {
    title: 'Obstruction',
    instructions: 'A wall blocks direct line of sight. Route through a gap at the top or bottom.',
    walls: [1, 2, 3, 4, 5, 6].map((y) => ({ x: 4, y })),
    sources: [{ color: 'blue', x: 0, y: 3, range: 3 }],
    receivers: [{ color: 'blue', x: 7, y: 3 }],
    budgets: { blue: 3 },
    relayRange: 3,
    interferenceDistance: 0,
  },
  {
    title: 'Cross Signals',
    instructions:
      'Two signals, one grid. Relays of different colors that get too close jam BOTH — route around, not through the middle.',
    walls: [],
    sources: [
      { color: 'blue', x: 0, y: 0, range: 3 },
      { color: 'red', x: 7, y: 0, range: 3 },
    ],
    receivers: [
      { color: 'blue', x: 7, y: 7 },
      { color: 'red', x: 0, y: 7 },
    ],
    budgets: { blue: 5, red: 5 },
    relayRange: 3,
    interferenceDistance: 2,
  },
  {
    title: 'Narrow Gap',
    walls: [0, 1, 2, 4, 5, 6, 7].map((y) => ({ x: 4, y })),
    sources: [{ color: 'blue', x: 0, y: 2, range: 3 }],
    receivers: [{ color: 'blue', x: 7, y: 4 }],
    budgets: { blue: 2 },
    relayRange: 3,
    interferenceDistance: 0,
  },
  {
    title: 'Stray Rock',
    instructions: 'One obstacle sits right on the direct line — a relay chain that hugs it too closely gets blocked.',
    walls: [
      { x: 3, y: 3 },
      { x: 4, y: 4 },
    ],
    sources: [{ color: 'blue', x: 0, y: 0, range: 3 }],
    receivers: [{ color: 'blue', x: 7, y: 7 }],
    budgets: { blue: 3 },
    relayRange: 3,
    interferenceDistance: 0,
  },
  {
    title: 'Short Hop',
    instructions: 'Relays here only reach half as far as before — the same distance now needs more of them.',
    walls: [],
    sources: [{ color: 'blue', x: 0, y: 7, range: 3 }],
    receivers: [{ color: 'blue', x: 7, y: 0 }],
    budgets: { blue: 5 },
    relayRange: 2,
    interferenceDistance: 0,
  },
  {
    title: 'Switchback',
    walls: [
      ...[0, 2, 3, 4, 5, 6, 7].map((y) => ({ x: 3, y })),
      ...[0, 1, 2, 3, 4, 6, 7].map((y) => ({ x: 5, y })),
    ],
    sources: [{ color: 'blue', x: 0, y: 2, range: 3 }],
    receivers: [{ color: 'blue', x: 7, y: 4 }],
    budgets: { blue: 4 },
    relayRange: 3,
    interferenceDistance: 0,
  },
  {
    title: 'Boxed In',
    walls: [
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 5, y: 5 },
      { x: 7, y: 3 },
      { x: 7, y: 4 },
      { x: 7, y: 5 },
      { x: 6, y: 5 },
    ],
    sources: [{ color: 'blue', x: 1, y: 6, range: 3 }],
    receivers: [{ color: 'blue', x: 6, y: 4 }],
    budgets: { blue: 3 },
    relayRange: 3,
    interferenceDistance: 0,
  },
  {
    title: 'Shared Lane',
    instructions: 'Both signals funnel through the same gap. Give them separate rows through it or they jam each other.',
    walls: [0, 1, 2, 6, 7].map((y) => ({ x: 4, y })),
    sources: [
      { color: 'blue', x: 0, y: 2, range: 3 },
      { color: 'red', x: 0, y: 6, range: 3 },
    ],
    receivers: [
      { color: 'blue', x: 7, y: 2 },
      { color: 'red', x: 7, y: 6 },
    ],
    budgets: { blue: 2, red: 2 },
    relayRange: 3,
    interferenceDistance: 2,
  },
  {
    title: 'Tight Squeeze',
    instructions: 'Red cuts straight across the middle. Blue has to go all the way around it, not just step aside.',
    walls: [],
    sources: [
      { color: 'blue', x: 0, y: 3, range: 3 },
      { color: 'red', x: 3, y: 0, range: 3 },
    ],
    receivers: [
      { color: 'blue', x: 7, y: 3 },
      { color: 'red', x: 3, y: 7 },
    ],
    budgets: { blue: 4, red: 3 },
    relayRange: 3,
    interferenceDistance: 2,
  },
  {
    title: 'Bent Signal',
    instructions:
      "The whole board is boxed in except the top row and right column. Ride the top row to the corner, bounce off the mirror, and head down the right column to the receiver.",
    // Everything except the top row (y=0) and right column (x=7) is wall --
    // the only route across the board is that L-shaped edge corridor.
    walls: GRID_X.flatMap((x) => GRID_Y.filter((y) => y !== 0 && x !== 7).map((y) => ({ x, y }))),
    mirrors: [{ x: 7, y: 0, orientation: 'back' }],
    sources: [{ color: 'blue', x: 0, y: 0, range: 6 }],
    receivers: [{ color: 'blue', x: 7, y: 7 }],
    budgets: { blue: 2 },
    relayRange: 4,
    interferenceDistance: 0,
  },
  {
    title: 'Double Bounce',
    instructions:
      'Same edge-hugging idea, but the only open path is three sides of the board -- up the left column, across the top, then down the right column, bouncing off a mirror at each corner.',
    // Everything except the left column (x=0), top row (y=0), and right
    // column (x=7) is wall -- a full perimeter loop, missing the bottom edge.
    walls: GRID_X.flatMap((x) => GRID_Y.filter((y) => y !== 0 && x !== 0 && x !== 7).map((y) => ({ x, y }))),
    mirrors: [
      { x: 0, y: 0, orientation: 'fwd' },
      { x: 7, y: 0, orientation: 'back' },
    ],
    sources: [{ color: 'blue', x: 0, y: 7, range: 6 }],
    receivers: [{ color: 'blue', x: 7, y: 7 }],
    budgets: { blue: 3 },
    relayRange: 5,
    interferenceDistance: 0,
  },
  {
    title: 'Signal Maze',
    instructions:
      'A proper maze this time: two of the four turns have a mirror to bend the beam for free, the other two are plain corners that need a relay of their own. Figure out which is which.',
    walls: wallsExcept([
      '0,7', '0,6', '0,5', '0,4', '0,3', '0,2', '0,1', '0,0',
      '1,0', '2,0', '3,0', '4,0',
      '4,1', '4,2', '4,3', '4,4',
      '5,4', '6,4', '7,4',
    ]),
    mirrors: [
      { x: 0, y: 0, orientation: 'fwd' }, // N (from source) -> E
      { x: 4, y: 4, orientation: 'back' }, // S (arriving) -> E
    ],
    sources: [{ color: 'blue', x: 0, y: 7, range: 11 }],
    receivers: [{ color: 'blue', x: 7, y: 4 }],
    budgets: { blue: 1 },
    relayRange: 7,
    interferenceDistance: 0,
  },
  {
    title: 'Mirror Junction',
    instructions: 'A tight staircase with a mirror at every step. Small board, six bounces -- watch the beam thread through all of them on its way to the receiver.',
    walls: wallsExcept([
      '0,0', '1,0', '2,0',
      '2,1',
      '2,2', '3,2', '4,2',
      '4,3',
      '4,4', '5,4', '6,4',
      '6,5',
      '6,6', '7,6',
    ]),
    mirrors: [
      { x: 2, y: 0, orientation: 'back' }, // E -> S
      { x: 2, y: 2, orientation: 'back' }, // S -> E
      { x: 4, y: 2, orientation: 'back' }, // E -> S
      { x: 4, y: 4, orientation: 'back' }, // S -> E
      { x: 6, y: 4, orientation: 'back' }, // E -> S
      { x: 6, y: 6, orientation: 'back' }, // S -> E
    ],
    sources: [{ color: 'blue', x: 0, y: 0, range: 6 }],
    receivers: [{ color: 'blue', x: 7, y: 6 }],
    budgets: { blue: 2 },
    relayRange: 4,
    interferenceDistance: 0,
  },
  {
    title: 'Decoy Fork',
    instructions:
      "The corridor forks after the bend. One branch is a dead end that goes nowhere -- don't waste your only relay finding out the hard way.",
    walls: wallsExcept([
      '0,0', '1,0', '2,0', '3,0', '4,0',
      '4,1', '4,2', '4,3', '4,4', '4,5', '4,6',
      '5,3', '6,3',
    ]),
    mirrors: [{ x: 4, y: 0, orientation: 'back' }], // E -> S
    sources: [{ color: 'blue', x: 0, y: 0, range: 6 }],
    receivers: [{ color: 'blue', x: 4, y: 6 }],
    budgets: { blue: 1 },
    relayRange: 4,
    interferenceDistance: 0,
  },
  {
    title: 'Reflective Chokepoint',
    instructions: 'A wall splits the board down the middle -- the only way through is a single mirror. Blue bounces south off it, red bounces east off that very same panel. Crowd a relay too close to the notch and you jam both signals at once.',
    walls: [
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 1, y: 5 },
      { x: 1, y: 6 },
      { x: 1, y: 7 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 2, y: 5 },
      { x: 2, y: 6 },
      { x: 2, y: 7 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 3, y: 5 },
      { x: 3, y: 6 },
      { x: 3, y: 7 },
      { x: 4, y: 0 },
      { x: 4, y: 5 },
      { x: 4, y: 6 },
      { x: 4, y: 7 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 5, y: 6 },
      { x: 5, y: 7 },
      { x: 6, y: 0 },
      { x: 6, y: 1 },
      { x: 6, y: 2 },
      { x: 6, y: 5 },
      { x: 6, y: 7 },
      { x: 7, y: 4 },
      { x: 7, y: 5 },
      { x: 7, y: 6 },
    ],
    mirrors: [{ x: 4, y: 3, orientation: 'back' }],
    sources: [{ color: 'blue', x: 0, y: 0, range: 4 }, { color: 'red', x: 0, y: 7, range: 7 }],
    receivers: [{ color: 'blue', x: 7, y: 7 }, { color: 'red', x: 7, y: 0 }],
    budgets: { blue: 2, red: 3 },
    relayRange: 5,
    interferenceDistance: 2,
  },
  {
    title: 'Mirror Crossfire',
    instructions: "Two mirrors, two colors, a walled-off middle. There's no straight line from your source to your receiver -- hug your own edge, bounce off your corner mirror, then hug the far edge in.",
    walls: [
      { x: 1, y: 6 },
      { x: 2, y: 5 },
      { x: 3, y: 4 },
      { x: 4, y: 3 },
      { x: 5, y: 2 },
      { x: 6, y: 1 },
      { x: 1, y: 5 },
      { x: 2, y: 4 },
      { x: 3, y: 3 },
      { x: 4, y: 2 },
      { x: 5, y: 1 },
      { x: 2, y: 6 },
      { x: 3, y: 5 },
      { x: 4, y: 4 },
      { x: 5, y: 3 },
      { x: 6, y: 2 },
    ],
    mirrors: [{ x: 0, y: 7, orientation: 'back' }, { x: 7, y: 0, orientation: 'back' }],
    sources: [{ color: 'blue', x: 7, y: 7, range: 4 }, { color: 'red', x: 0, y: 0, range: 4 }],
    receivers: [{ color: 'blue', x: 0, y: 1 }, { color: 'red', x: 7, y: 6 }],
    budgets: { blue: 2, red: 2 },
    relayRange: 5,
    interferenceDistance: 5,
  },
  {
    title: 'Shared Bend',
    instructions: 'Blue runs south down the center column into the mirror and bends east; red runs east along the center row into the same mirror and bends south. Both approach relays naturally want to sit right next to the mirror -- but that puts them within jamming range of each other. Back each one up one extra step on its own leg to clear the jam radius, using every bit of remaining reach to still make the bend.',
    walls: [
      { x: 0, y: 0 },
      { x: 0, y: 1 },
      { x: 0, y: 2 },
      { x: 0, y: 3 },
      { x: 0, y: 5 },
      { x: 0, y: 6 },
      { x: 0, y: 7 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 1, y: 5 },
      { x: 1, y: 6 },
      { x: 1, y: 7 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 3 },
      { x: 2, y: 5 },
      { x: 2, y: 6 },
      { x: 2, y: 7 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 3, y: 5 },
      { x: 3, y: 6 },
      { x: 3, y: 7 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 5, y: 3 },
      { x: 5, y: 5 },
      { x: 5, y: 6 },
      { x: 5, y: 7 },
      { x: 6, y: 0 },
      { x: 6, y: 1 },
      { x: 6, y: 2 },
      { x: 6, y: 3 },
      { x: 6, y: 5 },
      { x: 6, y: 6 },
      { x: 6, y: 7 },
      { x: 7, y: 0 },
      { x: 7, y: 1 },
      { x: 7, y: 2 },
      { x: 7, y: 3 },
      { x: 7, y: 5 },
      { x: 7, y: 6 },
      { x: 7, y: 7 },
    ],
    mirrors: [{ x: 4, y: 4, orientation: 'back' }],
    sources: [{ color: 'blue', x: 4, y: 0, range: 1 }, { color: 'red', x: 0, y: 4, range: 1 }],
    receivers: [{ color: 'blue', x: 7, y: 4 }, { color: 'red', x: 4, y: 7 }],
    budgets: { blue: 2, red: 2 },
    relayRange: 5,
    interferenceDistance: 2,
  },
  {
    title: 'Forked Lanes',
    instructions: 'Blue starts right in the one-cell-wide spine, red has to slip in beside it. Both of you need at least one relay on that shared column before you can branch off -- but relays less than 2 apart from the opposite color jam. Give the spine some room before you commit to your branch.',
    walls: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 4, y: 0 },
      { x: 5, y: 0 },
      { x: 6, y: 0 },
      { x: 7, y: 0 },
      { x: 0, y: 1 },
      { x: 1, y: 1 },
      { x: 2, y: 1 },
      { x: 4, y: 1 },
      { x: 5, y: 1 },
      { x: 6, y: 1 },
      { x: 7, y: 1 },
      { x: 0, y: 2 },
      { x: 1, y: 2 },
      { x: 2, y: 2 },
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
      { x: 7, y: 2 },
      { x: 0, y: 3 },
      { x: 1, y: 3 },
      { x: 2, y: 3 },
      { x: 0, y: 4 },
      { x: 1, y: 4 },
      { x: 2, y: 4 },
      { x: 4, y: 4 },
      { x: 5, y: 4 },
      { x: 6, y: 4 },
      { x: 0, y: 5 },
      { x: 1, y: 5 },
      { x: 2, y: 5 },
      { x: 4, y: 5 },
      { x: 5, y: 5 },
      { x: 6, y: 5 },
      { x: 0, y: 6 },
      { x: 4, y: 6 },
      { x: 5, y: 6 },
      { x: 6, y: 6 },
      { x: 1, y: 7 },
      { x: 2, y: 7 },
      { x: 3, y: 7 },
      { x: 4, y: 7 },
      { x: 5, y: 7 },
      { x: 6, y: 7 },
    ],
    sources: [{ color: 'red', x: 2, y: 0, range: 3 }, { color: 'blue', x: 3, y: 0, range: 3 }],
    receivers: [{ color: 'red', x: 0, y: 7 }, { color: 'blue', x: 7, y: 7 }],
    budgets: { red: 2, blue: 2 },
    relayRange: 5,
    interferenceDistance: 2,
  },
];

// Only the very first level gates on the (single, combined) tutorial; every
// other level skips straight to play, except the first level to introduce a
// new mechanic -- Bent Signal (mirrors) gates on its own short tutorial.
// See tutorialContent.tsx.
export const levelTutorialKey: Array<string | null> = [
  'all',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  'mirrors',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
];
