/**
 * Every sound effect the app can play. The WAVs are generated by
 * tools/sound-synth (`npm run sounds`) -- add a recipe there, then an entry
 * here.
 */
export type SoundId = 'tap' | 'place' | 'match' | 'error' | 'win' | 'fail';

export interface SoundSpec {
  source: number;
  /** Players kept for this sound, so rapid repeats (a drag crossing cells)
   * overlap instead of cutting each other off. */
  voices: number;
  /** Repeats closer together than this are dropped -- a fast drag shouldn't
   * turn into a buzz. */
  minGapMs: number;
}

export const SOUNDS: Record<SoundId, SoundSpec> = {
  tap: { source: require('../../assets/sounds/tap.wav'), voices: 3, minGapMs: 35 },
  place: { source: require('../../assets/sounds/place.wav'), voices: 3, minGapMs: 45 },
  match: { source: require('../../assets/sounds/match.wav'), voices: 2, minGapMs: 80 },
  error: { source: require('../../assets/sounds/error.wav'), voices: 1, minGapMs: 150 },
  win: { source: require('../../assets/sounds/win.wav'), voices: 1, minGapMs: 1000 },
  fail: { source: require('../../assets/sounds/fail.wav'), voices: 1, minGapMs: 1000 },
};

export const SOUND_IDS = Object.keys(SOUNDS) as SoundId[];
